Added added code needed to build for amd64, arm32 and arm64 processors
maxking/docker-mailman pull request #484
Opened 2021-08-08 20:13 UTC by colindawson

I used [this blog post](https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/) to make changes to the build.sh that should allow multi arch builds to take place.  This should allow the project to build for AMD64 as normal as well as for ARM both 32 and 64 bit.

2021-08-09 00:32 UTC, maxking requested changes
Overall, I think it would be a good change. I remember at least one person who asked me for arm images.

If you can also check whether any changes are required in the deploy script, then it would be awesome!

2021-08-09 00:32 UTC, maxking commented on build.sh
> +	for value in amd64 arm32v7 arm64v8
```suggestion
	for arch in amd64 arm32v7 arm64v8
```
Can you also rename the variables used below to `$arch` instead and other loops?

2021-08-09 00:33 UTC, maxking commented
Another thing is whether it would affect downloading of images on current users? Can they still continue to use the same tag to get new images or would they have to change something?

2021-08-09 09:00 UTC, colindawson commented
I'm not 100% sure if it will be seamless.  As this is the first time that I've attempted to do anything with docker image creation.
From what I understand, it should allow everything to carry on seamlessly as before.    The manifest means that if you try to download the image it'll check your OS and download the correct image.   The manifest takes the original tag name.
In addition people on other OS's should can work exactly the same and the manifest routes them to the correct image.

2021-08-09 09:32 UTC, colindawson reviewed
I've changed value to arch as requested, it's consistent through the whole file.

2021-11-30 22:15 UTC, colindawson commented
I guess this is going nowhere

2022-12-08 22:29 UTC, closed without merging